2019-12-01 02:17:45 DEBUG Logger Initialized
2019-12-01 02:20:16 ERROR Exception occurs in API module: list index out of range
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\fyle\date_extractor\Scripts\date_extractor_main.py", line 110, in extract_date
    date_in_dt = list(datefinder.find_dates(imageTextToken))[0]
IndexError: list index out of range
2019-12-01 02:21:08 DEBUG Logger Initialized
2019-12-01 03:13:42 DEBUG Logger Initialized
